connaisa/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include("connaisaV0.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

connaisaV0/urls.py
from django.conf.urls import url
from . import views

app_name = 'connaisaV0'
urlpatterns = [
    url(r'^index/', views.index, name="index"),
    url(r'^signup/$', views.signup, name="signup"),
    url(r'^login/$', views.login, name="login"),
    url(r'^logout/$', views.logout, name="logout"),
    url(r'^accounthome/', views.accounthome, name="accounthome"),
    url(r'^editprofile/', views.editProfile, name="editprofile"),
    url(r'^newpost/', views.newPost, name="newpost"),
    url(r'^post/(?P<post_id>\d+)/$', views.viewPost, name="viewpost"),
    url(r'^editpost/(?P<post_id>\d+)/$', views.editPost, name="editpost"),
    url(r'^userpage/(?P<user_id>\d+)/$', views.userPage, name="userpage"),
    #url(r'^search/', views.search, name="search"),
    #test use only
    url(r'^clean/', views.clean, name="clean"),
    url(r'^main/$', views.main, name="main"),
    url(r'^$', views.index, name="index"),

]

templates/base/base.html
{% load staticfiles %}
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html prefix="og: http://ogp.me/ns#"> <!--<![endif]-->
<html lang="en">
<head>
    <!-- BASICS -->
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- OPEN GRAPH PROTOCAL -->
    <meta property="og:title" content="Connaisa" />
    <meta property="og:url" content="https://connaisa.com/" />
    <meta property="og:image" content="{% static 'images/logo.png' %}" />

    <link rel="icon" href="{% static 'images/logo.png' %}" type="image/png">
    <link rel="stylesheet" type="text/css" href="{% static 'css/isotope.css' %}" media="screen" />
    <link rel="stylesheet" href="{% static 'js/fancybox/jquery.fancybox.css' %}" type="text/css" media="screen" />
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-theme.css' %}">
    <link rel="stylesheet" href="{% static 'css/con-style.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- skin -->
    <link rel="stylesheet" href="{% static 'skin/default.css' %}">
    <!-- w3 -->
    <link rel="stylesheet" href="{% static 'css/w3.css' %}">
    <!-- my css -->
    <link rel="stylesheet" href="{% static 'css/my-style.css' %}">
    <!-- content -->
    <meta name="keywords" content="{% block keyword %}Mandarin, Japanese, paino, guitar{% endblock keyword %}">
    <meta name="description" content="{% block description %}This is connaisa base page{% endblock description %}">
    <title>{% block pageTitle %}Connaisa Base Page{% endblock pageTitle %}</title>
</head>
<body>
{% include "base/header.html" %}
{% include "base/navigate.html" %}

<main>
    {% block mainbody %}
        Welcome to Connaisa V0.1 development.
        Main body part goes here. If you are seeing this, work still needs to be done.
    {% endblock mainbody %}
</main>

{% include "base/footer.html" %}
<script src="https://cdn.bootcss.com/jquery/2.1.1/jquery.min.js"></script>
<script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
</html>

templates/base/footer.html
<section id="footer" class="section footer">
    <div class="container">
        <div class="row animated opacity mar-bot20 mar-top20" data-andown="fadeIn" data-animation="animation">
            <div class="col-sm-12 align-center">
                <ul class="social-network social-circle">
                    <li><a href="https://www.facebook.com/Connaisa-247946152284475" target="_blank" title="Facebook"><i class="fa fa-facebook"></i></a></li>
                    <li><a href="https://twitter.com/connaisaco" target="_blank" title="Twitter"><i class="fa fa-twitter"></i></a></li>
                    <li><a href="https://www.linkedin.com/company/connaisa" target="_blank" title="Linkedin"><i class="fa fa-linkedin"></i></a></li>
                </ul>
            </div>
        </div>

        <div class="row align-center copyright">
            <div class="col-sm-12">
                <p>Copyright &copy; Amoeba</p>
            </div>
        </div>
    </div>
</section>

templates/base/header.html
{% load staticfiles %}
<section class="featured" id="home">
    <div class="container">
        <div class="row mar-bot40">
            <div class="col-xs-12 col-md-6">
                <div class="align-center">
                    <!--<div class="w3-content w3-display-container">-->
                    <div class="embed-container">
                      <iframe width="560" height="315" src="https://www.youtube.com/embed/9I0tgu58pO4" frameborder="0" allowfullscreen></iframe>
                    </div>
                </div>
            </div>
            <div class="col-xs-12 col-md-6">
                <div class="align-center mar-top-75 mar-left-50">
                    <h2 class="con-slogan">Exchange knowledge and skills with people around the world</h2>
                    {% if user.userid%}
                    <a href="{% url 'connaisaV0:accounthome'%}" class="btn bold btn-lg btn-blue border-rd-15">Account Home</a>
                    {% else %}
                    <a href="{% url 'connaisaV0:signup'%}" class="btn bold btn-lg btn-blue border-rd-15">Sign up</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</section>

templates/base/navigate.html
{% load static %}
<section id="header" class="appear"></section>
<div class="navbar navbar-fixed-top" role="navigation" data-0="line-height:100px; height:100px; background-color:rgba(0,0,0,0.3);" data-300="line-height:60px; height:60px; background-color:rgba(0,0,0,1);">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="fa fa-bars color-white"></span>
        </button>
        <a class="navbar-brand logo" href="{% url 'connaisaV0:index'%}" data-0="margin-top:25px;" data-300="margin-top:10px;">
            <img class="img-responsive" width="221.79" height="43.1" src="{% static 'images/logo.svg' %}">
        </a>
    </div>
    <div class="navbar-collapse collapse">
        {% if user.userid%}
            <a href="{% url 'connaisaV0:index'%}">Main page</a>
            <span class="dropdown" class="btn btn-blue border-rd-15">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    My account
                    <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="{% url 'connaisaV0:accounthome'%}">Account home</a></li>
                    <li><a href="#">My classes</a></li>
                    <li><a href="{% url 'connaisaV0:newpost'%}">Write a new post</a></li>
                    <li><a href="{% url 'connaisaV0:editprofile'%}">My profile</a></li>
                    <li><a href="{% url 'connaisaV0:logout'%}">Log out</a></li>
                </ul>
            </span>

            <a href="">About us</a>
        {% else %}
            <a href="{% url 'connaisaV0:index'%}">Main page</a>
            <a href="{% url 'connaisaV0:login'%}">Log in</a>
            <a href="{% url 'connaisaV0:signup'%}" class="btn btn-blue border-rd-15">Sign up</a>
            <a href="">About us</a>
        {% endif %}
    </div>
</div>