connaisa/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include("connaisaV0.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

connaisaV0/urls.py
from django.conf.urls import url
from . import views

app_name = 'connaisaV0'
urlpatterns = [
    url(r'^index/', views.index, name="index"),
    url(r'^signup/$', views.signup, name="signup"),
    url(r'^login/$', views.login, name="login"),
    url(r'^logout/$', views.logout, name="logout"),
    url(r'^accounthome/', views.accounthome, name="accounthome"),
    url(r'^editprofile/', views.editProfile, name="editprofile"),
    url(r'^newpost/', views.newPost, name="newpost"),
    url(r'^post/(?P<post_id>\d+)/$', views.viewPost, name="viewpost"),
    url(r'^editpost/(?P<post_id>\d+)/$', views.editPost, name="editpost"),
    url(r'^userpage/(?P<user_id>\d+)/$', views.userPage, name="userpage"),
    #url(r'^search/', views.search, name="search"),
    #test use only
    url(r'^clean/', views.clean, name="clean"),
    url(r'^main/$', views.main, name="main"),
    url(r'^$', views.index, name="index"),

]

templates/account.html
{% extends "base/base.html" %}
{% load static %}

{% block mainbody %}
    <h2>{{ message }}</h2>
    <h2>Welcome back! &nbsp;{{ user_profile.username|capfirst}},</h2>
    <!-- user profile -->
    <table id="profile">
        <tr>
            <h3>User Profile</h3>
        </tr>
        <tr>
            {% if user_profile.photo%}
                <img src="{{ user_profile.photo.url }}" alt="photo" style="width:100px;height:100px;">
            {% else %}
                <img src="{% static "images/timg.jpg" %}" alt="photo" style="width:100px;height:100px;">
            {% endif %}
        </tr>
        <tr>
        <td><label for="username">Username: </label></td>
        <td><p name="username" id="username">{{ user_profile.username }}</p></td>
        </tr>
        <tr>
        <td><label for="email">Email: </label></td>
        <td><p name="email" id="email">{{ user_profile.email }}</p></td>
        </tr>
        <tr>
            <td>
                {% if is_profile_complete%}
                    <p>Your profile looks fine!</p>
                {% else %}
                    <p>Tell us more about you!</p>
                {% endif %}
            </td>
        </tr>
        <tr>
            <td><a href="{% url 'connaisaV0:editprofile'%}">Edit my profile</a></td>
        </tr>
    </table>
    <!-- user description -->
    <form method = "post">
        <div class="header-right description">
            <div id="descriptionBox">
                <form id="descriptionForm">
                    <fieldset id="body">
                        <fieldset>
                            <label for="description">About me: </label>
                            {% if has_description%}
                                <textarea name="description" id="description" rows="8" cols="50"
                                          placeholder="Let us know you better!">
{{ user_profile.description }}
                                </textarea>
                            {% else %}
                                <textarea name="description" id="description" rows="8" cols="50"
                                          placeholder="Let us know you better!"></textarea>
                            {% endif %}
                        </fieldset>
                        <input type="submit" id="save_description" value="Save">
                    </fieldset>
                </form>
            </div>
        </div>
    </form>
    <!-- user's posts -->
    <h3>My post:</h3>
        <fieldset id="posts">
        {% for post in posts %}
            <fieldset id="post_{{ post.id }}">
                <a href="{% url 'connaisaV0:viewpost' post.id %}">
                    <p>{{ post.name }}</p>
                    <p>Category: {{ post.category }}</p>
                    <p>Level: {{ post.level}}</p>
                    <p>Status: {% if post.active %}Active{% else %}Inactive{% endif %}</p>
                    <P>Time posted: {{ post.time_created }}</P>
                </a>
            </fieldset>
        {% endfor %}
    </fieldset>

{% endblock mainbody %}

templates/editPost.html
{% extends "base/base.html" %}
{% load static %}

{% block mainbody %}
    <h2>{{ message }}</h2>
    <h2>Tell us more to make the post more attractive!</h2>
    <h3>Poster:
        {% if user_profile.photo%}
            <img src="{{ user_profile.photo.url }}" alt="photo" style="width:100px;height:100px;">
        {% else %}
            <img src="{% static "images/timg.jpg" %}" alt="photo" style="width:100px;height:100px;">
        {% endif %}
        {{ user_profile.username|capfirst }}({{ user_profile.email }})</h3>
    <form method = "post">
    <div class="header-right profile">
        <div id="postBox">
            <form id="postForm">
                <fieldset id="body">
                    <fieldset>
                        <label for="postname">Post Name: </label>
                        <input type="text" name="postname" id="postname" size="60" placeholder="Describe your post!"
                               value="{{ post_info.postname }}" required>
                    </fieldset>
                    <fieldset>
                        <label for="category">Category: </label>
                        <select name="category" id="category">
                            <option value="0">Art</option>
                            <option value="1">Sports</option>
                            <option value="2">Language</option>
                            <option value="3">Academic</option>
                            <option value="4">Living</option>
                            <option value="5">other</option>
                        </select>
                    </fieldset>
                    <fieldset>
                        <label for="level">Level: </label>
                        <select name="level" id="level">
                            <option value="0">Beginner</option>
                            <option value="1">Amateur</option>
                            <option value="2">Intermediate</option>
                            <option value="3">Proficient</option>
                            <option value="4">Expert</option>
                        </select>
                    </fieldset>
                    <fieldset>
                        <label for="description">Description: </label>
                        <textarea name="description" id="description" rows="12" cols="62"
                                  placeholder="Let us know your post better!" required>{{ post_info.description }}</textarea>
                    </fieldset>
                    {% if not post_info.newpost%}
                        <fieldset>
                        <table >
                            <tr>
                            <th><label for="active">Active: </label></th>
                            <th><input type="checkbox" name="active" id="active" /></th>
                            </tr>
                            <tr>
                            <th><label for="delete">Delete post: </label></th>
                            <th><input type="checkbox" name="delete" id="delete" onchange="deletionAlert()" /></th>
                            </tr>
                        </table>
                        </fieldset>
                    {% endif %}
                    {% if post_info.newpost%}
                        <input type="submit" id="post" value="Post!">
                    {% else %}
                        <input type="submit" id="save" value="Save">
                    {% endif %}
                </fieldset>
            </form>
        </div>
    </div>
    </form>
<script  type="text/javascript">
document.getElementById("category")[{{ post_info.category }}].selected=true;
document.getElementById("level")[{{ post_info.level }}].selected=true;
function deletionAlert() {
    if(document.getElementById("delete").checked==true){
        alert('Are you sure? Deletion is not reversible.\nIf you do wish to delete this post, go ahead and click the save button.');
    }
}
{% if not post_info.newpost%}
    {% if post_info.active%}
        document.getElementById("active").checked=true;
    {% endif %}
{% endif %}
</script>
{% endblock mainbody %}

templates/editProfile.html
{% extends "base/base.html" %}
{% load static %}

{% block mainbody %}
    <h2>{{ message }}</h2>
    <h2>My Profile:</h2>
    <h3>Email: {{ user_profile.email }}</h3>
    <form method = "post" enctype="multipart/form-data">
    <div class="header-right profile">
        <div id="profileBox">
            <form id="profileForm">
                <fieldset id="body">
                    <fieldset>
                        <label for="username">Username: </label>
                        <input type="text" name="username" id="username" value="{{ user_profile.username }}" required>
                    </fieldset>
                    <fieldset>
                        <label for="name">Name: </label>
                        <input type="text" name="name" id="name" value="{{ user_profile.name }}">
                    </fieldset>
                    <fieldset>
                        <label for="gender">Gender: </label>
                        <select name="gender" id="gender">
                            <option hidden="true" value="0">Select your gender</option>
                            <option value="1">Male</option>
                            <option value="2">Female</option>
                            <option value="3">other</option>
                        </select>
                    </fieldset>
                    <fieldset>
                        <label for="date_of_birth">Date of birth: </label>
                        <input type="date" name="date_of_birth" id="date_of_birth" defaultValue="{{ user_profile.dateofbirth }}">
                    </fieldset>
                    <fieldset>
                        <label for="address">Address: </label>
                        <input type="text" name="address" id="address" value="{{ user_profile.address }}">
                    </fieldset>
                    <fieldset>
                        <div>
                            <label for="number">Phone number: </label>
                            <input type="tel" name="number" id="number"
                                   minlength="9" maxlength="12"
                                   placeholder="123-456-7890"
                                   pattern="[0-9]{3}-[0-9]{3}-[0-9]{4}"
                                   value="{{ user_profile.number }}" />
                            <span class="validity"></span>
                        </div>
                    </fieldset>
                    <fieldset>
                        <table >
                            <tr>
                            <th><label for="photo">Photo: </label></th>
                            <th><label for="current_photo">Currtent Photo</label></th>
                            </tr>
                            <tr>
                            <td><input type="file" name="photo" id="photo"></td>
                            <td>
                                {% if user_profile.photo%}
                                <img src="{{ user_profile.photo.url }}" alt="photo" style="width:100px;height:100px;">
                                {% else %}
                                <img src="{% static "images/timg.jpg" %}" alt="photo" style="width:100px;height:100px;">
                                {% endif %}
                            </td>
                            </tr>
                        </table>
                    </fieldset>
                    <input type="submit" id="save_profile" value="Save">
                </fieldset>
            </form>
        </div>
    </div>
    </form>

<script  type="text/javascript">
document.getElementById("gender")[{{ user_profile.gender }}].selected=true;
</script>
{% endblock mainbody %}

templates/index.html
{% extends "base/base.html" %}
{% load static %}

{% block mainbody %}
    <!-- search -->
    <h2>{{ message }}</h2>
    <section class="cm-searching" id="search_bar">
        <div class="class=row mar-bot40">
            <div class="align-center">
               <form>
                <input type="text" id="search" name="search" placeholder="Search any keywords!" required>
                <input type="submit" id="submitsearch" value="Search!"/>
              </form>
                <p>Popular searches: <a href="/?search=guitar">guitar, &nbsp;</a> <a href="/?search=japanese">japanese, &nbsp;</a></p>
            </div>
        </div>
    </section>
    <!-- about -->
    <section id="section-about" class="con-section appear clearfix">
        <div class="container">

            <div class="section-header">
                <h2 class="section-heading animated mar-bot30" data-animation="bounceInUp">What is Connaisa?</h2>
                <div class="row">
                    <div class="col-xs-12 col-md-5 col-md-offset-1 mar-top50">
                        <div class="align-left">
                            <i class="fa fa-quote-left fa-lg con-blue" aria-hidden="true"></i>
                        </div>
                        <h4 class="align-left mar-left30">A platform to</h4>
                        <h4 class="align-left mar-left30">teach and learn knowledge and skills</h4>
                        <h4 class="align-right mar-right30">with people around the world</h4>
                        <div class="align-right">
                            <i class="fa fa-quote-right fa-lg con-green" aria-hidden="true"></i>
                        </div>
                    </div>

                    <div class="col-xs-12 col-md-5">
                        <div class="embed-container">
                        <iframe width="487.5" height="315" src="https://www.youtube.com/embed/V0fvMRjv_HA" frameborder="0" allowfullscreen></iframe>
                        </div>
                    </div>
                </div>
            </div>
        </div>
            <br>
            <div class="section-header mar-top40">
                <h2 class="section-heading animated mar-bot10" data-animation="bounceInUp">How to use Connaisa?</h2>
                <!--<img width="1000" src="img/howtoconn.svg">-->
                <img class="con-img-responsive" width="1000" src="{% static "images/howtoconn.svg" %}">
            </div>
            <br>
            <div class="section-header mar-top40">
                <h2 class="section-heading animated mar-bot10" data-animation="bounceInUp">You are both Coner and Conee</h2>
                <img class="con-img-responsive" width="980" height="481.69" src="{% static "images/coner-conee.svg" %}">
            </div>
            <div class="section-header mar-top40">
                <div class="row">
                    <div class="col-md-offset-7 col-md-5">
                        <h3 class="mar-bot10 con-blue" id="more-details" data-animation="bounceInUp" onclick="showDetails()">more details about Connaisa...</h3>
                    </div>
                </div>
            </div>
            <div class="mar-top40 align-left" id="details" style="margin-left:100px; margin-right:100px">
                <p>Connaisa is a platform to freely exchange knowledge and skills with people around the world. Users select the subjects they are interested to teach and learn. Then, our system automatically matches the users with the same interests. Coners, the teachers, provide courses; while Conees, the students, take courses. They can directly interact with one another through posts, video chats, instant messages, and public broadcasts.</p>
                <br>
                <h3>Matching Coners and Conees</h3>
                <p>Our matching system automatically suggests the best matches to the users, based on the interests of their choices. Users can also actively search for teaching or learning opportunities via other users’ profile pages. Coners can increase their search performance by sponsoring the platform. Furthermore, Connaisa provides online storage spaces for Coners to store their teaching materials, which can be posted on their personal profile pages (handouts, videos, demos, etc.). Coners decide whether the materials are public or can only be viewed with permission.</p>
                <br>
                <h3>Direct Interactions with Other Users</h3>
                <p>Users can interact with other users: posts, instant messages, video chats, and public broadcasting. First, users can post questions and comments under other users’ profile pages with permission. The owners of the page can leave corresponding answers and replies. Second, with instant messaging, users can directly communicate with other users in words. Third, through our video chat feature, Coners can easily provide Conees with one-on-one lectures, allowing instant interactions. Last, with our public broadcasting feature, Coners can provide one-to-many lectures and have online face-to-face group discussions and activities.</p>
                <br>
                <h3>Connaisa Coin System</h3>
                <p>Connaisa Coins (hereinafter referred as “Coins”) are designed for the transactions between users in the platform. Users gain Coins in two ways - users can earn Coins by providing courses or they can purchase Coins from our platform. Coins can be used to take courses on the platform or cashed out. The exchange rate of USD and Coins will be fixed. We will charge processing fee for every transaction between users.</p>
                <br>
                <h3>Goal of Connaisa</h3>
                <p>Our ultimate goal is to eliminate the inequality of educational resources. We believe that knowledge and skills are sharing economy. We are enthusiastic about creating a world where people share learning resources. Currently, customers need to pay to learn new knowledge and skills. However, with our platform, customers will teach their own expertise in exchange for learning new knowledge and skills. Our goal is to make learning resources costless, freely exchangeable, and publicly accessible. We look forward that one day Connaisa will lead the world towards educational equality.</p>
            </div>
        </div>
    </section>

    <!-- contact -->
    <section id="section-contact" class="con-section back-blue appear clearfix">
        <div class="container">

            <div class="row mar-bot40">
                <div class="col-md-offset-3 col-md-6">
                    <div class="section-header">
                        <h2 class="section-heading animated" data-animation="bounceInUp">Contact us</h2>
                        <p>Thank you for your interest in our educational platform. Please leave your message. We will soon get back to you.</p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-8 col-md-offset-2">
                    <div class="cform contact-form">
                        <div class="sendmessage" id="contactSendmessage">
                             Your message has been sent. Thank you!
                        </div>
                        <form action="" method="post" role="form" class="contactForm" id="contact-form">
                          <div class="form-group pad-bot30 align-center" id="queryType">
                            <input type="radio" name="contact-type" value="feedback"><span class="mar-right30 mar-left5">Feedback</span>
                            <input type="radio" name="contact-type" value="media"><span class="mar-right30 mar-left5">Media Inquiry</span>
                            <input type="radio" name="contact-type" value="join"><span class="mar-right30 mar-left5">Join Our Team</span>
                            <input type="radio" name="contact-type" value="join"><span class="mar-right30 mar-left5">Sponsor Us</span>
                            <input type="radio" name="contact-type" value="join"><span class="mar-right30 mar-left5">Other</span>
                          </div>
                          <div class="form-group">
                            <label for="name">Name*</label>
                            <input type="text" name="con_name" class="form-control" id="contactName"/>
                            <div class="validation" id="con_name_validation"></div>
                          </div>
                          <div class="form-group">
                            <label for="email">Email*</label>
                            <input type="email" class="form-control" name="con_email" id="contactEmail" data-msg="Please enter a valid email" />
                            <div class="validation" id="con_email_validation"></div>
                          </div>
                          <div class="form-group">
                            <label for="message">Message</label>
                            <textarea class="form-control" name="message" id="contactMessage" rows="5"></textarea>
                          </div>
                          <div class="align-center">
                            <button type="submit" class="btn bold btn-lg btn-blue border-rd-15" onclick="contactSubmit();">Send Message</button>
                          </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>
        <div class="align-center">
            <iframe src="https://www.google.com/maps/embed/v1/place?key=AIzaSyBhtw6Yk257IJoCUA6g96ULQKBV0NAGLdY&q=Siebel+Center,Illinois+US" width="1000" height="500"></iframe>
        </div>
    </section>
{% endblock mainbody %}

templates/login.html
{% extends "base/base.html" %}
{% load static %}

{% block mainbody %}
    <h2>{{ message }}</h2>
    <form method = "post">
        <div class="header-right login">
            <div id="loginBox">
                <form id="loginForm">
                    <fieldset id="body">
                        <fieldset>
                            <label for="email">Email Address</label>
                            <input type="text" name="email" id="email">
                        </fieldset>
                        <fieldset>
                            <label for="password">Password</label>
                            <input type="password" name="password" id="password">
                        </fieldset>
                        <input type="submit" id="login" value="Sign in">
                        <label for="forget_pw"><a href="#">Forgot your password?</a></label>
                    </fieldset>
                </form>
            </div>
        </div>
    </form>
{% endblock mainbody %}

templates/post.html
{% extends "base/base.html" %}
{% load static %}

{% block mainbody %}
    <h2>{{ message }}</h2>
    <h3>Post name: {{ post_info.postname }}</h3>
    <p>Category: {{ post_info.category }}</p>
    <p>Level: {{ post_info.level }}</p>
    <p>Description: {{ post_info.description }}</p>
    {% if post_info.poster_photo%}
        <img src="{{ post_info.poster_photo.url }}" alt="photo" style="width:100px;height:100px;">
    {% else %}
        <img src="{% static "images/timg.jpg" %}" alt="photo" style="width:100px;height:100px;">
    {% endif %}
    <div>
        <a href="{% url 'connaisaV0:userpage' post_info.poster_id%}">Poster: {{ post_info.poster_name|capfirst}}</a>
    </div>
    <p>Status:
        {% if post_info.active%}
            &nbsp;&nbsp;Active
        {% else %}
            &nbsp;&nbsp;Inactive
        {% endif %}
    </p>
    {% if editable%}
        <a href="{% url 'connaisaV0:editpost' post_info.id %}">Edit post</a>
    {% else %}
        <a href="#">Contact poster</a>
        <a href="#">Register this class!</a>
    {% endif %}
{% endblock mainbody %}

templates/search.html
{% extends "base/base.html" %}
{% load static %}

{% block mainbody %}
<h2>{{ message }}</h2>
<div class="search">
	<div class="s-bar">
	   <form>
		<input type="text" id="search" name="search" placeholder="Search any keywords!" required>
		<input type="submit" name="submitsearch" value="Search!"/>
	   </form>
	</div>
</div>
<h3>Search result for <b>{{ search_content }}</b>:</h3>
<p>{{ post_count }}&nbsp;results</p>
<!-- search results-->

<div class="search">
    <fieldset id="body">
        {% for post in search_posts %}
            <fieldset id="post_{{ post.id }}">
                <a href="{% url 'connaisaV0:viewpost' post.id %}">
                    <p>{{ post.name }}</p>
                    <p>Category: {{ post.category }}</p>
                    <p>Level: {{ post.level}}</p>
                    <p>Status: {% if post.active %}Active{% else %}Inactive{% endif %}</p>
                    <p>Poster: {{ post.poster.username|capfirst }}</p>
                    <P>Time posted: {{ post.time_created }}</P>
                </a>
            </fieldset>
        {% endfor %}
    </fieldset>
</div>

{% endblock mainbody %}

templates/signup.html
{% extends "base/base.html" %}
{% load static %}

{% block mainbody %}
    <h2>{{ message }}</h2>
    <form method = "post">
    <div class="header-right login">
        <div id="loginBox">
            <form id="loginForm">
                <fieldset id="body">
                    <fieldset>
                        <label for="username">Username: </label>
                        <input type="text" name="username" id="username">
                    </fieldset>
                    <fieldset>
                        <label for="email">Email Address: </label>
                        <input type="text" name="email" id="email">
                    </fieldset>
                    <fieldset>
                        <label for="password">Password: </label>
                        <input type="password" name="password" id="password">
                    </fieldset>
                    <fieldset>
                        <label for="secureQ">Secure Question: </label>
                        <select name="secureQ" id="secureQ">
                            <option hidden="true" value="1">What is your home country?</option>
                            <option value="2">When is your best friend's birthday?</option>
                            <option value="3">What is the name of your first pet?</option>
                            <option value="4">What is your father's name?</option>
                            <option value="5">What is your favourite food?</option>
                            <option value="6">What is the brand of your first car?</option>
                            <option value="7">What is your mother's name?</option>
                        </select>
                    </fieldset>
                    <fieldset>
                        <label for="secureA">Your answer: </label>
                        <input type="text" name="secureA" id="secureA">
                    </fieldset>
                    <input type="submit" id="login" value="Sign up!">
                    <label for="checkbox"><input type="checkbox" id="checkbox"> <i>Remember me</i></label>
                </fieldset>
            </form>
        </div>
    </div>
    </form>
{% endblock mainbody %}

templates/userPage.html
{% extends "base/base.html" %}
{% load static %}

{% block mainbody %}
    <h2>{{ message }}</h2>
    <h2>{{ user_profile.username|capfirst}}</h2>
    <span>Membership since: {{ user_profile.time_created.date}}</span>
    <!-- user profile -->
    <table id="profile">
        <tr>
            <h3>User Profile</h3>
        </tr>
        <tr>
            {% if user_profile.photo%}
                <img src="{{ user_profile.photo.url }}" alt="photo" style="width:100px;height:100px;">
            {% else %}
                <img src="{% static "images/timg.jpg" %}" alt="photo" style="width:100px;height:100px;">
            {% endif %}
        </tr>
        <tr>
        <td><label for="username">Username: </label></td>
        <td><p name="username" id="username">{{ user_profile.username }}</p></td>
        </tr>
        <tr>
        <td><label for="email">Email: </label></td>
        <td><p name="email" id="email">{{ user_profile.email }}</p></td>
        </tr>
    </table>
    <!-- user description -->
            <h4>Introduction: </h4>
            <p>
            {% if has_description%}
                {{ user_profile.description }}
            {% else %}
                This user does not have any introduction.
            {% endif %}
            </p>

    <!-- user's posts -->
    <h3>Posts:</h3>
    <fieldset id="posts">
        {% for post in posts %}
            <fieldset id="post_{{ post.id }}">
                <a href="{% url 'connaisaV0:viewpost' post.id %}">
                    <p>{{ post.name }}</p>
                    <p>Category: {{ post.category }}</p>
                    <p>Level: {{ post.level}}</p>
                    <p>Status: {% if post.active %}Active{% else %}Inactive{% endif %}</p>
                    <P>Time posted: {{ post.time_created }}</P>
                </a>
            </fieldset>
        {% endfor %}
    </fieldset>

{% endblock mainbody %}